/**
 * CineWave Entertainment - Pega Movie Ticket Booking System
 * Seed Data & Database Store
 * Designed & Developed by Kathirvel T
 */

const CineWaveInitialData = {
    // Current Indian & Global Blockbuster Movies with high-res verified posters
    movies: [
        {
            id: "MOV-001",
            title: "The Greatest of All Time (GOAT)",
            language: "Tamil",
            genre: "Action / Sci-Fi / Thriller",
            duration: "3h 03m",
            certification: "U/A",
            rating: 8.4,
            votes: "142.5K",
            releaseDate: "05 Sep 2024",
            startingPrice: 150,
            status: "Now Showing",
            director: "Venkat Prabhu",
            cast: "Thalapathy Vijay, Prashanth, Prabhu Deva, Sneha, Meenakshi Chaudhary",
            description: "A former elite member of the Special Anti-Terrorist Squad (SATS) is summoned back into action when an old vendetta threatens the nation and his own estranged family.",
            posterUrl: "assets/goat_poster.png",
            backdropUrl: "assets/goat_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: true
        },
        {
            id: "MOV-002",
            title: "Vettaiyan",
            language: "Tamil",
            genre: "Action / Crime / Drama",
            duration: "2h 48m",
            certification: "U/A",
            rating: 8.6,
            votes: "118.2K",
            releaseDate: "10 Oct 2024",
            startingPrice: 160,
            status: "Now Showing",
            director: "T. J. Gnanavel",
            cast: "Superstar Rajinikanth, Amitabh Bachchan, Fahadh Faasil, Rana Daggubati, Manju Warrier",
            description: "A principled encounter specialist takes on the corruption within the educational and corporate nexus, triggering a philosophical confrontation with the justice system.",
            posterUrl: "assets/vettaiyan_poster.jpg",
            backdropUrl: "assets/vettaiyan_poster.jpg",
            trailerUrl: "https://www.youtube.com",
            featured: true
        },
        {
            id: "MOV-003",
            title: "Amaran",
            language: "Tamil",
            genre: "Biographical / Action / Drama",
            duration: "2h 49m",
            certification: "U/A",
            rating: 9.1,
            votes: "165.8K",
            releaseDate: "31 Oct 2024",
            startingPrice: 140,
            status: "Now Showing",
            director: "Rajkumar Periasamy",
            cast: "Sivakarthikeyan, Sai Pallavi, Bhuvan Arora, Rahul Bose",
            description: "The gripping real-life chronicle of Major Mukund Varadarajan (AC), an Indian Army officer who laid down his life leading a counter-terrorism operation in Kashmir.",
            posterUrl: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=600&q=80",
            backdropUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
            trailerUrl: "https://www.youtube.com",
            featured: true
        },
        {
            id: "MOV-004",
            title: "Coolie",
            language: "Tamil",
            genre: "Action / Thriller / Heist",
            duration: "2h 55m",
            certification: "U/A",
            rating: 8.8,
            votes: "89.4K",
            releaseDate: "01 May 2025",
            startingPrice: 180,
            status: "Now Showing",
            director: "Lokesh Kanagaraj",
            cast: "Superstar Rajinikanth, Nagarjuna, Soubin Shahir, Shruti Haasan, Sathyaraj",
            description: "An enigmatic union leader with a lethal past orchestrates an underground gold smuggling interception against high-profile crime syndicates.",
            posterUrl: "https://images.unsplash.com/photo-1616530940355-351fabd9524b?auto=format&fit=crop&w=600&q=80",
            backdropUrl: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1200&q=80",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },
        {
            id: "MOV-005",
            title: "Kalki 2898 AD",
            language: "Telugu",
            genre: "Sci-Fi / Epic / Mythological",
            duration: "3h 01m",
            certification: "U/A",
            rating: 8.7,
            votes: "210.0K",
            releaseDate: "27 Jun 2024",
            startingPrice: 180,
            status: "Now Showing",
            director: "Nag Ashwin",
            cast: "Prabhas, Amitabh Bachchan, Kamal Haasan, Deepika Padukone, Disha Patani",
            description: "In the post-apocalyptic desert city of Kasi in 2898 AD, an immortal warrior awaits the avatar destined to overthrow the Supreme Yaskin's totalitarian reign.",
            posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
            backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },
        {
            id: "MOV-006",
            title: "Pushpa 2: The Rule",
            language: "Telugu",
            genre: "Action / Crime / Drama",
            duration: "3h 21m",
            certification: "A",
            rating: 8.9,
            votes: "195.4K",
            releaseDate: "05 Dec 2024",
            startingPrice: 170,
            status: "Now Showing",
            director: "Sukumar",
            cast: "Allu Arjun, Rashmika Mandanna, Fahadh Faasil, Jagapathi Babu",
            description: "Pushpa Raj expands his red sandalwood empire beyond borders while confronting SP Bhanwar Singh Shekhawat in a violent battle for absolute dominance.",
            posterUrl: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=600&q=80",
            backdropUrl: "https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?auto=format&fit=crop&w=1200&q=80",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },
        {
            id: "MOV-007",
            title: "Deadpool & Wolverine",
            language: "English",
            genre: "Action / Comedy / Sci-Fi",
            duration: "2h 08m",
            certification: "A",
            rating: 8.3,
            votes: "320.1K",
            releaseDate: "26 Jul 2024",
            startingPrice: 200,
            status: "Now Showing",
            director: "Shawn Levy",
            cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin, Matthew Macfadyen",
            description: "The Time Variance Authority pulls Wade Wilson out of his quiet life, teaming him up with a reluctant Wolverine to save his universe from catastrophic collapse.",
            posterUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80",
            backdropUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },
        {
            id: "MOV-008",
            title: "Interstellar (IMAX Re-Release)",
            language: "English",
            genre: "Sci-Fi / Adventure / Drama",
            duration: "2h 49m",
            certification: "U/A",
            rating: 9.3,
            votes: "450.0K",
            releaseDate: "27 Sep 2024",
            startingPrice: 250,
            status: "Now Showing",
            director: "Christopher Nolan",
            cast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine",
            description: "When Earth faces extinction, a team of astronauts embarks through a wormhole near Saturn in search of a habitable new home for humanity across time and space.",
            posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
            backdropUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1200&q=80",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },
        {
            id: "MOV-009",
            title: "Jana Nayagan (Thalapathy 69)",
            language: "Tamil",
            genre: "Political / Action / Drama",
            duration: "2h 50m",
            certification: "U/A",
            rating: 9.4,
            votes: "182.6K",
            releaseDate: "Oct 2025",
            startingPrice: 190,
            status: "Now Showing",
            director: "H. Vinoth",
            cast: "Thalapathy Vijay, Pooja Hegde, Bobby Deol, Gautham Vasudev Menon, Priyamani, Prakash Raj",
            description: "A charismatic people's leader rises against systemic injustice and corporate political collusion. An Anirudh musical spectacle produced by KVN Productions.",
            posterUrl: "assets/jana_nayagan_poster.png",
            backdropUrl: "assets/jana_nayagan_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: true
        }
    ],

    // Theatres across key Tamil Nadu & South Indian Cities
    theatres: [
        {
            id: "THT-001",
            name: "CineWave Luxe Cinemas – Chennai",
            location: "Chennai",
            address: "Express Avenue Mall, Royapettah, Chennai - 600014",
            screens: ["Screen 1 – IMAX Laser", "Screen 2 – Dolby Atmos", "Screen 3 – 4DX Experience", "Screen 4 – VIP Gold Class"],
            facilities: ["Dolby Atmos 7.1", "IMAX with Laser", "4DX Motion", "Gourmet Dining", "Recliner Loungers", "Valet Parking"],
            status: "Active"
        },
        {
            id: "THT-002",
            name: "CineWave Grand Cineplex – Madurai",
            location: "Madurai",
            address: "Bypass Road, Ponmeni, Madurai - 625016",
            screens: ["Screen 1 – Dolby Atmos 4K", "Screen 2 – IMAX Grand", "Screen 3 – CineWave Standard"],
            facilities: ["Dolby Atmos", "4K RGB Laser", "VIP Recliner Seating", "Food Court", "EV Charging"],
            status: "Active"
        },
        {
            id: "THT-003",
            name: "CineWave Platinum – Coimbatore",
            location: "Coimbatore",
            address: "Brookefields Mall, Krishnaswamy Road, Coimbatore - 641001",
            screens: ["Screen 1 – IMAX 3D", "Screen 2 – Atmos Premier", "Screen 3 – Recliner Suite"],
            facilities: ["IMAX 3D", "Dolby 64-Channel Atmos", "Plush Recliners", "Snack Bar"],
            status: "Active"
        },
        {
            id: "THT-004",
            name: "CineWave Regal – Trichy",
            location: "Trichy",
            address: "Cantonment High Road, Trichy - 620001",
            screens: ["Screen 1 – Dolby 4K", "Screen 2 – CineWave Atmos", "Screen 3 – Economy Standard"],
            facilities: ["Dolby Sound", "Air Conditioned", "Online Seat Selection", "Ample Parking"],
            status: "Active"
        },
        {
            id: "THT-005",
            name: "CineWave City Plaza – Karur",
            location: "Karur",
            address: "Kovai Road, Karur - 639002",
            screens: ["Screen 1 – Dolby 7.1 Atmos", "Screen 2 – Standard 2K"],
            facilities: ["Dolby Surround 7.1", "Pushback Ergonomic Seats", "Cafeteria"],
            status: "Active"
        },
        {
            id: "THT-006",
            name: "CineWave Superplex – Bengaluru",
            location: "Bengaluru",
            address: "Phoenix Marketcity, Whitefield, Bengaluru - 560048",
            screens: ["Screen 1 – IMAX GT", "Screen 2 – VIP Director's Cut", "Screen 3 – 4DX Atmos"],
            facilities: ["IMAX 12-Channel", "VIP Butler Service", "4DX Dynamic", "Ultra HD Projection"],
            status: "Active"
        },
        {
            id: "THT-007",
            name: "CineWave MegaScreen – Hyderabad",
            location: "Hyderabad",
            address: "Inorbit Mall, Hitech City, Hyderabad - 500081",
            screens: ["Screen 1 – BigScreen Atmos", "Screen 2 – Recliner Club", "Screen 3 – IMAX 3D"],
            facilities: ["Dual Laser IMAX", "Dolby Atmos 128-Track", "Live Kitchen", "Free Wi-Fi"],
            status: "Active"
        }
    ],

    // Screens metadata
    screens: [
        { id: "SCR-001", name: "Screen 1 – IMAX Laser", theatreId: "THT-001", type: "IMAX", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-002", name: "Screen 2 – Dolby Atmos", theatreId: "THT-001", type: "Regular", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-003", name: "Screen 3 – 4DX Experience", theatreId: "THT-001", type: "VIP", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-004", name: "Screen 4 – VIP Gold Class", theatreId: "THT-001", type: "Recliner", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-005", name: "Screen 1 – Dolby Atmos 4K", theatreId: "THT-002", type: "Regular", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-006", name: "Screen 2 – IMAX Grand", theatreId: "THT-002", type: "IMAX", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-007", name: "Screen 1 – IMAX 3D", theatreId: "THT-003", type: "IMAX", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 }
    ],

    // Active Shows data object
    shows: [
        {
            id: "SHW-101",
            movieId: "MOV-001",
            theatreId: "THT-001",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "10:30 AM",
            endTime: "01:33 PM",
            showType: "IMAX",
            ticketPrice: 280,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "B3", "B4", "C2", "C3", "C4", "D5", "D6", "F1", "F2", "H3", "H4", "H5", "H6"],
            status: "Available"
        },
        {
            id: "SHW-102",
            movieId: "MOV-001",
            theatreId: "THT-001",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "02:45 PM",
            endTime: "05:48 PM",
            showType: "IMAX",
            ticketPrice: 320,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "A3", "A4", "A5", "A6", "B1", "B2", "B3", "B4", "B5", "B6", "C1", "C2", "C3", "C4", "C5", "C6", "D1", "D2", "D3", "D4", "D5", "D6", "E1", "E2", "E3", "E4", "E5", "E6", "F1", "F2", "F3", "F4", "F5", "F6", "G1", "G2", "G3", "G4", "G5", "G6", "H1", "H2", "H3", "H4"],
            status: "Almost Full"
        },
        {
            id: "SHW-103",
            movieId: "MOV-001",
            theatreId: "THT-001",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "07:00 PM",
            endTime: "10:03 PM",
            showType: "IMAX",
            ticketPrice: 350,
            totalSeats: 48,
            bookedSeats: ["A1","A2","A3","A4","A5","A6","B1","B2","B3","B4","B5","B6","C1","C2","C3","C4","C5","C6","D1","D2","D3","D4","D5","D6","E1","E2","E3","E4","E5","E6","F1","F2","F3","F4","F5","F6","G1","G2","G3","G4","G5","G6","H1","H2","H3","H4","H5","H6"],
            status: "Sold Out"
        },
        {
            id: "SHW-104",
            movieId: "MOV-002",
            theatreId: "THT-001",
            screenId: "SCR-002",
            date: "2026-08-28",
            startTime: "11:15 AM",
            endTime: "02:03 PM",
            showType: "Regular",
            ticketPrice: 190,
            totalSeats: 48,
            bookedSeats: ["A3", "A4", "B1", "B2", "C5", "C6", "E3", "E4"],
            status: "Available"
        },
        {
            id: "SHW-105",
            movieId: "MOV-002",
            theatreId: "THT-001",
            screenId: "SCR-004",
            date: "2026-08-28",
            startTime: "06:30 PM",
            endTime: "09:18 PM",
            showType: "Recliner",
            ticketPrice: 350,
            totalSeats: 48,
            bookedSeats: ["G1", "G2", "H1", "H2", "H3"],
            status: "Available"
        },
        {
            id: "SHW-106",
            movieId: "MOV-003",
            theatreId: "THT-002",
            screenId: "SCR-005",
            date: "2026-08-28",
            startTime: "10:00 AM",
            endTime: "12:49 PM",
            showType: "Regular",
            ticketPrice: 160,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "B1", "B2", "C3", "C4"],
            status: "Available"
        },
        {
            id: "SHW-107",
            movieId: "MOV-003",
            theatreId: "THT-002",
            screenId: "SCR-006",
            date: "2026-08-28",
            startTime: "07:30 PM",
            endTime: "10:19 PM",
            showType: "IMAX",
            ticketPrice: 280,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "C1", "C2", "D3", "D4", "E1", "E2", "E3", "F4", "F5"],
            status: "Available"
        },
        {
            id: "MOV-SHW-108",
            movieId: "MOV-004",
            theatreId: "THT-001",
            screenId: "SCR-003",
            date: "2026-08-28",
            startTime: "09:45 PM",
            endTime: "12:40 AM",
            showType: "VIP",
            ticketPrice: 380,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "A3", "B1", "B2"],
            status: "Available"
        },
        {
            id: "MOV-SHW-109",
            movieId: "MOV-007",
            theatreId: "THT-006",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "04:15 PM",
            endTime: "06:23 PM",
            showType: "IMAX",
            ticketPrice: 350,
            totalSeats: 48,
            bookedSeats: ["A1", "B1", "B2", "C1", "C2", "C3", "D1", "D2", "E4", "E5"],
            status: "Available"
        },
        {
            id: "MOV-SHW-110",
            movieId: "MOV-008",
            theatreId: "THT-003",
            screenId: "SCR-007",
            date: "2026-08-28",
            startTime: "08:15 PM",
            endTime: "11:04 PM",
            showType: "IMAX",
            ticketPrice: 320,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "A3", "B4", "B5", "C2", "C3", "D1", "D2"],
            status: "Available"
        },
        {
            id: "SHW-111",
            movieId: "MOV-009",
            theatreId: "THT-001",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "11:00 AM",
            endTime: "01:50 PM",
            showType: "IMAX",
            ticketPrice: 300,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "B1", "B2", "C3", "C4", "E5", "E6"],
            status: "Available"
        },
        {
            id: "SHW-112",
            movieId: "MOV-009",
            theatreId: "THT-002",
            screenId: "SCR-006",
            date: "2026-08-28",
            startTime: "06:45 PM",
            endTime: "09:35 PM",
            showType: "IMAX",
            ticketPrice: 280,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "D1", "D2", "E1", "E2"],
            status: "Available"
        },
        {
            id: "SHW-113",
            movieId: "MOV-009",
            theatreId: "THT-003",
            screenId: "SCR-007",
            date: "2026-08-28",
            startTime: "09:30 PM",
            endTime: "12:20 AM",
            showType: "VIP",
            ticketPrice: 350,
            totalSeats: 48,
            bookedSeats: ["A3", "A4", "B5", "B6"],
            status: "Available"
        }
    ],

    // Existing Pega Cases to demonstrate Work Queues, Routing, SLA, and Lifecycle
    cases: [
        {
            pyID: "C-1001",
            bookingId: "CW20260828001",
            ticketId: "TKT-90412",
            customerId: "CUST-001",
            customerName: "Kavitha Raman",
            email: "kavitha.r@gmail.com",
            mobile: "+91 98401 23456",
            movieId: "MOV-001",
            movieTitle: "The Greatest of All Time (GOAT)",
            theatreId: "THT-001",
            theatreName: "CineWave Luxe Cinemas – Chennai",
            location: "Chennai",
            screenId: "SCR-001",
            screenName: "Screen 1 – IMAX Laser",
            showId: "SHW-101",
            showDate: "2026-08-28",
            showTime: "10:30 AM",
            showType: "IMAX",
            ticketCategory: "VIP",
            ticketCount: 2,
            seats: ["H5", "H6"],
            ticketPrice: 280,
            categoryMultiplier: 1.5,
            subtotal: 840,
            convenienceFee: 80,
            taxAmount: 151.2,
            totalAmount: 1071.2,
            pyStatusWork: "Resolved-Completed",
            currentStageIndex: 7, // Notify Customer / Completed
            assignedWorkbasket: "Premium Cinema Team",
            routingReason: "Auto-routed via US-010: Show Type = IMAX -> Premium Cinema Team",
            createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
            slaGoalMinutes: 10,
            slaDeadlineMinutes: 30,
            urgency: 40,
            slaStatus: "Within SLA",
            rejectionReason: "",
            auditTrail: [
                { time: "45 mins ago", actor: "Kavitha Raman (Customer)", action: "Booking request submitted (US-001)", stage: "Submit Booking Request" },
                { time: "44 mins ago", actor: "Pega Engine (System)", action: "Show seats validated & locked (US-002)", stage: "Check Show Availability" },
                { time: "44 mins ago", actor: "Pega Engine (System)", action: "Cost calculated: ₹1,071.20 (US-003)", stage: "Calculate Booking Cost" },
                { time: "43 mins ago", actor: "Kavitha Raman (Customer)", action: "Customer confirmed booking details (US-004)", stage: "Customer Confirmation" },
                { time: "42 mins ago", actor: "Pega Routing Router", action: "Case routed to 'Premium Cinema Team' (US-010)", stage: "Route Case" },
                { time: "38 mins ago", actor: "Arun (Staff - Premium Team)", action: "Booking approved & processed (US-006 & US-007)", stage: "Process Ticket Booking" },
                { time: "38 mins ago", actor: "Pega Notification Engine", action: "SMS & Email sent with QR Ticket (US-008)", stage: "Notify Customer" },
                { time: "38 mins ago", actor: "Pega Engine (System)", action: "Case Resolved-Completed", stage: "Case Completion" }
            ]
        },
        {
            pyID: "C-1002",
            bookingId: "CW20260828002",
            ticketId: "TKT-82941",
            customerId: "CUST-002",
            customerName: "Kathirvel T",
            email: "kathirvel.dev@cinewave.in",
            mobile: "+91 94432 98765",
            movieId: "MOV-002",
            movieTitle: "Vettaiyan",
            theatreId: "THT-002",
            theatreName: "CineWave Grand Cineplex – Madurai",
            location: "Madurai",
            screenId: "SCR-006",
            screenName: "Screen 2 – IMAX Grand",
            showId: "SHW-107",
            showDate: "2026-08-28",
            showTime: "07:30 PM",
            showType: "IMAX",
            ticketCategory: "Premium",
            ticketCount: 3,
            seats: ["E1", "E2", "E3"],
            ticketPrice: 280,
            categoryMultiplier: 1.25,
            subtotal: 1050,
            convenienceFee: 120,
            taxAmount: 189,
            totalAmount: 1359,
            pyStatusWork: "Resolved-Completed",
            currentStageIndex: 7,
            assignedWorkbasket: "Premium Cinema Team",
            routingReason: "Auto-routed via US-010: Show Type = IMAX -> Premium Cinema Team",
            createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
            slaGoalMinutes: 10,
            slaDeadlineMinutes: 30,
            urgency: 25,
            slaStatus: "Within SLA",
            rejectionReason: "",
            auditTrail: [
                { time: "25 mins ago", actor: "Kathirvel T (Customer)", action: "Submitted VIP booking request", stage: "Submit Booking Request" },
                { time: "24 mins ago", actor: "Pega Engine", action: "Calculated ₹1,359 with IMAX premium", stage: "Calculate Booking Cost" },
                { time: "23 mins ago", actor: "Kathirvel T", action: "Confirmed details", stage: "Customer Confirmation" },
                { time: "20 mins ago", actor: "Meena (Staff)", action: "Approved and generated TKT-82941", stage: "Process Ticket Booking" },
                { time: "20 mins ago", actor: "System", action: "Dispatched In-App and Email notifications", stage: "Notify Customer" }
            ]
        },
        {
            pyID: "C-1003",
            bookingId: "CW20260828003",
            ticketId: "",
            customerId: "CUST-003",
            customerName: "Praveen Kumar",
            email: "praveen.k@gmail.com",
            mobile: "+91 97890 54321",
            movieId: "MOV-003",
            movieTitle: "Amaran",
            theatreId: "THT-001",
            theatreName: "CineWave Luxe Cinemas – Chennai",
            location: "Chennai",
            screenId: "SCR-004",
            screenName: "Screen 4 – VIP Gold Class",
            showId: "SHW-105",
            showDate: "2026-08-28",
            showTime: "06:30 PM",
            showType: "Recliner",
            ticketCategory: "Recliner",
            ticketCount: 2,
            seats: ["G1", "G2"],
            ticketPrice: 350,
            categoryMultiplier: 1.4,
            subtotal: 980,
            convenienceFee: 80,
            taxAmount: 176.4,
            totalAmount: 1236.4,
            pyStatusWork: "Pending-Review",
            currentStageIndex: 3, // Review Booking Details
            assignedWorkbasket: "Premium Seating Team",
            routingReason: "Auto-routed via US-010: Show Type = Recliner -> Premium Seating Team",
            createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
            slaGoalMinutes: 10,
            slaDeadlineMinutes: 30,
            urgency: 65,
            slaStatus: "Approaching Deadline",
            rejectionReason: "",
            auditTrail: [
                { time: "14 mins ago", actor: "Praveen Kumar (Customer)", action: "Submitted Recliner booking request", stage: "Submit Booking Request" },
                { time: "13 mins ago", actor: "Pega Engine", action: "Show seats verified. Calculated ₹1,236.40", stage: "Calculate Booking Cost" },
                { time: "12 mins ago", actor: "Praveen Kumar", action: "Confirmed details", stage: "Customer Confirmation" },
                { time: "12 mins ago", actor: "Pega Router", action: "Routed to 'Premium Seating Team' (US-010)", stage: "Route Case" },
                { time: "4 mins ago", actor: "SLA Monitor", action: "SLA Goal passed (10m). Urgency increased to 65. Warning badge set.", stage: "SLA Escalation" }
            ]
        },
        {
            pyID: "C-1004",
            bookingId: "CW20260828004",
            ticketId: "",
            customerId: "CUST-004",
            customerName: "Senthil Nathan",
            email: "senthil.n@outlook.com",
            mobile: "+91 99400 11223",
            movieId: "MOV-004",
            movieTitle: "Coolie",
            theatreId: "THT-001",
            screenId: "SCR-003",
            theatreName: "CineWave Luxe Cinemas – Chennai",
            location: "Chennai",
            screenName: "Screen 3 – 4DX Experience",
            showId: "MOV-SHW-108",
            showDate: "2026-08-28",
            showTime: "09:45 PM",
            showType: "VIP",
            ticketCategory: "VIP",
            ticketCount: 3,
            seats: ["A1", "A2", "A3"],
            ticketPrice: 380,
            categoryMultiplier: 1.5,
            subtotal: 1710,
            convenienceFee: 120,
            taxAmount: 307.8,
            totalAmount: 2137.8,
            pyStatusWork: "Pending-Review",
            currentStageIndex: 3, // Review Booking Details
            assignedWorkbasket: "VIP Booking Team",
            routingReason: "Auto-routed via US-010: Show Type = VIP -> VIP Booking Team",
            createdAt: new Date(Date.now() - 34 * 60 * 1000).toISOString(),
            slaGoalMinutes: 10,
            slaDeadlineMinutes: 30,
            urgency: 95,
            slaStatus: "SLA Breached",
            rejectionReason: "",
            auditTrail: [
                { time: "34 mins ago", actor: "Senthil Nathan", action: "Created VIP case", stage: "Submit Booking Request" },
                { time: "33 mins ago", actor: "Pega Router", action: "Routed to 'VIP Booking Team'", stage: "Route Case" },
                { time: "4 mins ago", actor: "SLA Monitor", action: "DEADLINE BREACHED (30m+). Urgency set to 95. Escalated to Manager.", stage: "SLA Escalation" }
            ]
        }
    ],

    // Routing Workbaskets Definition (US-010)
    workbaskets: [
        { id: "WB-IMAX", name: "Premium Cinema Team", showType: "IMAX", description: "Specialized team managing high-tier IMAX Screen experiences", count: 1 },
        { id: "WB-VIP", name: "VIP Booking Team", showType: "VIP", description: "Handles 4DX, VIP Lounge and special requests", count: 1 },
        { id: "WB-RECLINER", name: "Premium Seating Team", showType: "Recliner", description: "Oversees Gold Class and Recliner Loungers", count: 1 },
        { id: "WB-REGULAR", name: "Standard Booking Team", showType: "Regular", description: "Standard Dolby Atmos & 2K screens bookings", count: 0 }
    ],

    // SLA Rules Specification (US-009)
    slaConfig: {
        goalMinutes: 10,
        deadlineMinutes: 30,
        passedDeadlineMinutes: 45,
        intervals: [
            { range: "0–10 mins", status: "Within SLA", badgeClass: "badge-success", urgencyRange: "0–40" },
            { range: "10–20 mins", status: "Approaching Deadline", badgeClass: "badge-warning", urgencyRange: "41–70" },
            { range: "20–30 mins", status: "High Priority", badgeClass: "badge-danger", urgencyRange: "71–89" },
            { range: "30+ mins", status: "SLA Breached", badgeClass: "badge-breached", urgencyRange: "90–100" }
        ]
    },

    // Pega Lifecycle Stages
    caseStages: [
        { index: 0, name: "Submit Booking Request", desc: "US-001: Capture Customer & Ticket Details" },
        { index: 1, name: "Check Show Availability", desc: "US-002: Real-time Seat Validation" },
        { index: 2, name: "Calculate Booking Cost", desc: "US-003: Automated Pricing Formula" },
        { index: 3, name: "Review Booking Details", desc: "US-006: Staff Review & Case Routing (US-010)" },
        { index: 4, name: "Customer Confirmation", desc: "US-004: Mandatory Customer Review & Ack" },
        { index: 5, name: "Process Ticket Booking", desc: "US-007: Seat Locking & Case Escalation" },
        { index: 6, name: "Generate Ticket", desc: "US-007 / Sec 19: Digital QR Ticket Generation" },
        { index: 7, name: "Notify Customer", desc: "US-008: Multi-channel SMS/Email/In-App Alert" }
    ],

    // Simulated notifications
    notifications: [
        {
            id: "NOTIF-1",
            title: "Booking Confirmed - GOAT",
            channel: "SMS & Email",
            time: "45 mins ago",
            recipient: "+91 98401 23456 | kavitha.r@gmail.com",
            message: "CineWave: Your booking CW20260828001 for The Greatest of All Time at CineWave Luxe Chennai on 28 Aug 10:30 AM is confirmed! Seats: H5, H6. Ticket: TKT-90412.",
            read: false
        },
        {
            id: "NOTIF-2",
            title: "Booking Confirmed - Vettaiyan",
            channel: "SMS & In-App",
            time: "20 mins ago",
            recipient: "+91 94432 98765 | kathirvel.dev@cinewave.in",
            message: "CineWave: Your booking CW20260828002 for Vettaiyan (IMAX Grand) at Madurai is confirmed! Seats: E1, E2, E3. Ticket: TKT-82941.",
            read: false
        }
    ]
};
