/**
 * CineWave Entertainment - Tamil Movie Ticket Booking System
 * Complete Database Store with July 2026 & August 2026 Tamil Movies
 * Designed & Developed by Kathirvel T
 */

const CineWaveInitialData = {
    // Verified Tamil Movies released in August 2026 (This Month) and July 2026 (Last Month)
    movies: [
        // ==========================================
        // 1. RELEASED THIS MONTH – AUGUST 2026
        // ==========================================
        {
            id: "MOV-001",
            tamilTitle: "தி கிரேட்டஸ்ட் ஆஃப் ஆல் டைம்",
            englishTitle: "The Greatest of All Time (GOAT)",
            title: "The Greatest of All Time (GOAT)",
            releaseCategory: "August 2026",
            releaseCategoryLabel: "Released This Month – Aug 2026",
            language: "Tamil",
            genre: "Action / Sci-Fi / Thriller",
            duration: "3h 03m",
            certification: "U/A",
            rating: 8.8,
            votes: "148.5K",
            releaseDate: "28 Aug 2026",
            startingPrice: 160,
            status: "Now Showing",
            director: "Venkat Prabhu",
            cast: "Thalapathy Vijay, Prashanth, Prabhu Deva, Sneha, Meenakshi Chaudhary, Mohan",
            description: "A former elite officer of the Special Anti-Terrorist Squad (SATS) must confront a catastrophic high-tech vendetta threatening the nation and his own estranged family.",
            posterUrl: "assets/goat_poster.png",
            backdropUrl: "assets/goat_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: true
        },
        {
            id: "MOV-002",
            tamilTitle: "ஜனநாயகன்",
            englishTitle: "Jana Nayagan (Thalapathy 69)",
            title: "Jana Nayagan (Thalapathy 69)",
            releaseCategory: "August 2026",
            releaseCategoryLabel: "Released This Month – Aug 2026",
            language: "Tamil",
            genre: "Political / Action / Drama",
            duration: "2h 50m",
            certification: "U/A",
            rating: 9.4,
            votes: "192.3K",
            releaseDate: "15 Aug 2026",
            startingPrice: 190,
            status: "Now Showing",
            director: "H. Vinoth",
            cast: "Thalapathy Vijay, Pooja Hegde, Bobby Deol, Gautham Vasudev Menon, Priyamani, Prakash Raj",
            description: "A charismatic visionary people's leader takes on deep-rooted systemic corruption and corporate political nexus. An Anirudh musical spectacle produced by KVN Productions.",
            posterUrl: "assets/jana_nayagan_poster.png",
            backdropUrl: "assets/jana_nayagan_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: true
        },
        {
            id: "MOV-003",
            tamilTitle: "இதயம் முரளி",
            englishTitle: "Idhayam Murali",
            title: "Idhayam Murali",
            releaseCategory: "August 2026",
            releaseCategoryLabel: "Released This Month – Aug 2026",
            language: "Tamil",
            genre: "Romantic / Comedy / Drama",
            duration: "2h 25m",
            certification: "U",
            rating: 8.6,
            votes: "84.1K",
            releaseDate: "08 Aug 2026",
            startingPrice: 150,
            status: "Now Showing",
            director: "Aakash Baskaran",
            cast: "Atharvaa Murali, Preethi Asrani, VTV Ganesh, Karunakaran",
            description: "A heartwarming, laugh-out-loud comedy about true one-sided love and unwavering friendship. A Thaman S musical presented by Dawn Pictures.",
            posterUrl: "assets/idhayam_murali_poster.png",
            backdropUrl: "assets/idhayam_murali_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },
        {
            id: "MOV-004",
            tamilTitle: "வாழை",
            englishTitle: "Vaazhai",
            title: "Vaazhai",
            releaseCategory: "August 2026",
            releaseCategoryLabel: "Released This Month – Aug 2026",
            language: "Tamil",
            genre: "Drama / Social / Realism",
            duration: "2h 15m",
            certification: "U",
            rating: 9.1,
            votes: "68.7K",
            releaseDate: "23 Aug 2026",
            startingPrice: 140,
            status: "Now Showing",
            director: "Mari Selvaraj",
            cast: "Ponvel, Raghul, Kalaiyarasan, Nikhila Vimal, J. Satish Kumar",
            description: "A deeply moving tale based on the childhood memories of director Mari Selvaraj, exploring innocent dreams and hardships of plantain farm workers. Music by Santhosh Narayanan.",
            posterUrl: "assets/vaazhai_poster.jpg",
            backdropUrl: "assets/vaazhai_poster.jpg",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },
        {
            id: "MOV-005",
            tamilTitle: "கொட்டுக்காளி",
            englishTitle: "Kottukkaali (The Rooster)",
            title: "Kottukkaali",
            releaseCategory: "August 2026",
            releaseCategoryLabel: "Released This Month – Aug 2026",
            language: "Tamil",
            genre: "Drama / Thriller",
            duration: "1h 45m",
            certification: "U/A",
            rating: 8.7,
            votes: "52.4K",
            releaseDate: "23 Aug 2026",
            startingPrice: 130,
            status: "Now Showing",
            director: "P. S. Vinothraj",
            cast: "Soori, Anna Ben",
            description: "A young woman's defiance against family patriarchal traditions triggers an intense road journey across rural Tamil Nadu. Acclaimed at Berlin International Film Festival.",
            posterUrl: "assets/kottukkaali_poster.png",
            backdropUrl: "assets/kottukkaali_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },

        // ==========================================
        // 2. RELEASED LAST MONTH – JULY 2026
        // ==========================================
        {
            id: "MOV-006",
            tamilTitle: "வேட்டையன்",
            englishTitle: "Vettaiyan",
            title: "Vettaiyan",
            releaseCategory: "July 2026",
            releaseCategoryLabel: "Released Last Month – Jul 2026",
            language: "Tamil",
            genre: "Action / Crime / Drama",
            duration: "2h 48m",
            certification: "U/A",
            rating: 8.7,
            votes: "135.2K",
            releaseDate: "25 Jul 2026",
            startingPrice: 160,
            status: "Now Showing",
            director: "T. J. Gnanavel",
            cast: "Superstar Rajinikanth, Amitabh Bachchan, Fahadh Faasil, Rana Daggubati, Manju Warrier",
            description: "A decorated encounter specialist encounters moral questions when unearthing a deep-seated scam in educational and corporate institutions. An Anirudh musical.",
            posterUrl: "assets/vettaiyan_poster.jpg",
            backdropUrl: "assets/vettaiyan_poster.jpg",
            trailerUrl: "https://www.youtube.com",
            featured: true
        },
        {
            id: "MOV-007",
            tamilTitle: "அமரன்",
            englishTitle: "Amaran",
            title: "Amaran",
            releaseCategory: "July 2026",
            releaseCategoryLabel: "Released Last Month – Jul 2026",
            language: "Tamil",
            genre: "Biographical / Action / Drama",
            duration: "2h 49m",
            certification: "U/A",
            rating: 9.3,
            votes: "185.8K",
            releaseDate: "18 Jul 2026",
            startingPrice: 150,
            status: "Now Showing",
            director: "Rajkumar Periasamy",
            cast: "Sivakarthikeyan, Sai Pallavi, Bhuvan Arora, Rahul Bose, Geetha Kailasam",
            description: "The gripping real-life chronicle of Major Mukund Varadarajan (Ashoka Chakra), an Indian Army officer who led heroic counter-terrorism operations with the 44 Rashtriya Rifles.",
            posterUrl: "assets/amaran_poster.png",
            backdropUrl: "assets/amaran_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: true
        },
        {
            id: "MOV-008",
            tamilTitle: "ராயன்",
            englishTitle: "Raayan",
            title: "Raayan",
            releaseCategory: "July 2026",
            releaseCategoryLabel: "Released Last Month – Jul 2026",
            language: "Tamil",
            genre: "Action / Crime / Revenge",
            duration: "2h 25m",
            certification: "A",
            rating: 8.5,
            votes: "120.4K",
            releaseDate: "26 Jul 2026",
            startingPrice: 150,
            status: "Now Showing",
            director: "Dhanush",
            cast: "Dhanush, S. J. Suryah, Sundeep Kishan, Kalidas Jayaram, Dushara Vijayan, Selvaraghavan",
            description: "A fast-food cook with a lethal past is dragged back into the ruthless North Chennai underworld when his brothers get embroiled in gang violence. Music by A. R. Rahman.",
            posterUrl: "assets/raayan_poster.png",
            backdropUrl: "assets/raayan_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },
        {
            id: "MOV-009",
            tamilTitle: "மகாராஜா",
            englishTitle: "Maharaja",
            title: "Maharaja",
            releaseCategory: "July 2026",
            releaseCategoryLabel: "Released Last Month – Jul 2026",
            language: "Tamil",
            genre: "Action / Mystery / Thriller",
            duration: "2h 21m",
            certification: "U/A",
            rating: 9.0,
            votes: "160.2K",
            releaseDate: "12 Jul 2026",
            startingPrice: 140,
            status: "Now Showing",
            director: "Nithilan Saminathan",
            cast: "Vijay Sethupathi, Anurag Kashyap, Mamta Mohandas, Natty (Natraj), Abhirami",
            description: "A humble barber embarks on an unyielding quest to recover his stolen dustbin named Lakshmi, unraveling a sinister crime syndicate.",
            posterUrl: "assets/maharaja_poster.png",
            backdropUrl: "assets/maharaja_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: false
        },
        {
            id: "MOV-010",
            tamilTitle: "கருடன்",
            englishTitle: "Garudan",
            title: "Garudan",
            releaseCategory: "July 2026",
            releaseCategoryLabel: "Released Last Month – Jul 2026",
            language: "Tamil",
            genre: "Action / Rural Drama",
            duration: "2h 14m",
            certification: "U/A",
            rating: 8.4,
            votes: "95.1K",
            releaseDate: "05 Jul 2026",
            startingPrice: 130,
            status: "Now Showing",
            director: "R. S. Durai Senthilkumar",
            cast: "Soori, M. Sasikumar, Unni Mukundan, Revathi Sharma, Samuthirakani",
            description: "An extraordinarily loyal confidant finds himself torn between two childhood brothers when land disputes and greed threaten to tear their village apart.",
            posterUrl: "assets/garudan_poster.png",
            backdropUrl: "assets/garudan_poster.png",
            trailerUrl: "https://www.youtube.com",
            featured: false
        }
    ],

    // Theatres across key Tamil Nadu Cities
    theatres: [
        {
            id: "THT-001",
            name: "CineWave Luxe Cinemas – Chennai",
            location: "Chennai",
            address: "Express Avenue Mall, Royapettah, Chennai - 600014",
            screens: ["Screen 1 – IMAX Laser", "Screen 2 – Dolby Atmos", "Screen 3 – 4DX Experience", "Screen 4 – VIP Gold Class"],
            facilities: ["Dolby Atmos 7.1", "IMAX with Laser", "4DX Motion", "Gourmet Dining", "Recliner Loungers", "Valet Parking"],
            status: "Active"
        },
        {
            id: "THT-002",
            name: "CineWave Grand Cineplex – Madurai",
            location: "Madurai",
            address: "Bypass Road, Ponmeni, Madurai - 625016",
            screens: ["Screen 1 – Dolby Atmos 4K", "Screen 2 – IMAX Grand", "Screen 3 – CineWave Standard"],
            facilities: ["Dolby Atmos", "4K RGB Laser", "VIP Recliner Seating", "Food Court", "EV Charging"],
            status: "Active"
        },
        {
            id: "THT-003",
            name: "CineWave Platinum – Coimbatore",
            location: "Coimbatore",
            address: "Brookefields Mall, Krishnaswamy Road, Coimbatore - 641001",
            screens: ["Screen 1 – IMAX 3D", "Screen 2 – Atmos Premier", "Screen 3 – Recliner Suite"],
            facilities: ["IMAX 3D", "Dolby 64-Channel Atmos", "Plush Recliners", "Snack Bar"],
            status: "Active"
        },
        {
            id: "THT-004",
            name: "CineWave Regal – Trichy",
            location: "Trichy",
            address: "Cantonment High Road, Trichy - 620001",
            screens: ["Screen 1 – Dolby 4K", "Screen 2 – CineWave Atmos", "Screen 3 – Economy Standard"],
            facilities: ["Dolby Sound", "Air Conditioned", "Online Seat Selection", "Ample Parking"],
            status: "Active"
        },
        {
            id: "THT-005",
            name: "CineWave City Plaza – Karur",
            location: "Karur",
            address: "Kovai Road, Karur - 639002",
            screens: ["Screen 1 – Dolby 7.1 Atmos", "Screen 2 – Standard 2K"],
            facilities: ["Dolby Surround 7.1", "Pushback Ergonomic Seats", "Cafeteria"],
            status: "Active"
        },
        {
            id: "THT-006",
            name: "CineWave ARRS Cineplex – Salem",
            location: "Salem",
            address: "Meyyanur Bypass, Salem - 636004",
            screens: ["Screen 1 – Dolby 4K Laser", "Screen 2 – CineWave Atmos"],
            facilities: ["RGB 4K Laser", "Dolby 7.1 Surround", "Wide Armchair Seating", "Food Hub"],
            status: "Active"
        }
    ],

    // Screens metadata
    screens: [
        { id: "SCR-001", name: "Screen 1 – IMAX Laser", theatreId: "THT-001", type: "IMAX", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-002", name: "Screen 2 – Dolby Atmos", theatreId: "THT-001", type: "Regular", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-003", name: "Screen 3 – 4DX Experience", theatreId: "THT-001", type: "VIP", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-004", name: "Screen 4 – VIP Gold Class", theatreId: "THT-001", type: "Recliner", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-005", name: "Screen 1 – Dolby Atmos 4K", theatreId: "THT-002", type: "Regular", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-006", name: "Screen 2 – IMAX Grand", theatreId: "THT-002", type: "IMAX", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 },
        { id: "SCR-007", name: "Screen 1 – IMAX 3D", theatreId: "THT-003", type: "IMAX", totalSeats: 48, rows: ["A", "B", "C", "D", "E", "F", "G", "H"], cols: 6 }
    ],

    // Active Shows across movies
    shows: [
        // GOAT Shows (MOV-001)
        {
            id: "SHW-101",
            movieId: "MOV-001",
            theatreId: "THT-001",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "10:30 AM",
            endTime: "01:33 PM",
            showType: "IMAX",
            ticketPrice: 280,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "B3", "B4", "C2", "C3", "C4", "D5", "D6", "F1", "F2", "H3", "H4", "H5", "H6"],
            status: "Available"
        },
        {
            id: "SHW-102",
            movieId: "MOV-001",
            theatreId: "THT-001",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "02:45 PM",
            endTime: "05:48 PM",
            showType: "IMAX",
            ticketPrice: 320,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "A3", "A4", "A5", "A6", "B1", "B2", "B3", "B4", "B5", "B6", "C1", "C2", "C3", "C4", "C5", "C6", "D1", "D2", "D3", "D4", "D5", "D6", "E1", "E2", "E3", "E4", "E5", "E6", "F1", "F2", "F3", "F4", "F5", "F6", "G1", "G2", "G3", "G4", "G5", "G6", "H1", "H2", "H3", "H4"],
            status: "Almost Full"
        },
        {
            id: "SHW-103",
            movieId: "MOV-001",
            theatreId: "THT-001",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "07:00 PM",
            endTime: "10:03 PM",
            showType: "IMAX",
            ticketPrice: 350,
            totalSeats: 48,
            bookedSeats: ["A1","A2","A3","A4","A5","A6","B1","B2","B3","B4","B5","B6","C1","C2","C3","C4","C5","C6","D1","D2","D3","D4","D5","D6","E1","E2","E3","E4","E5","E6","F1","F2","F3","F4","F5","F6","G1","G2","G3","G4","G5","G6","H1","H2","H3","H4","H5","H6"],
            status: "Sold Out"
        },
        // Jana Nayagan Shows (MOV-002)
        {
            id: "SHW-104",
            movieId: "MOV-002",
            theatreId: "THT-001",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "11:00 AM",
            endTime: "01:50 PM",
            showType: "IMAX",
            ticketPrice: 300,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "B1", "B2", "C3", "C4", "E5", "E6"],
            status: "Available"
        },
        {
            id: "SHW-105",
            movieId: "MOV-002",
            theatreId: "THT-002",
            screenId: "SCR-006",
            date: "2026-08-28",
            startTime: "06:45 PM",
            endTime: "09:35 PM",
            showType: "IMAX",
            ticketPrice: 280,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "D1", "D2", "E1", "E2"],
            status: "Available"
        },
        // Idhayam Murali Shows (MOV-003)
        {
            id: "SHW-106",
            movieId: "MOV-003",
            theatreId: "THT-001",
            screenId: "SCR-002",
            date: "2026-08-28",
            startTime: "01:15 PM",
            endTime: "03:40 PM",
            showType: "Regular",
            ticketPrice: 190,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "B3", "B4", "C1", "C2"],
            status: "Available"
        },
        {
            id: "SHW-107",
            movieId: "MOV-003",
            theatreId: "THT-004",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "06:15 PM",
            endTime: "08:40 PM",
            showType: "Regular",
            ticketPrice: 150,
            totalSeats: 48,
            bookedSeats: ["B1", "B2", "D3", "D4"],
            status: "Available"
        },
        // Vaazhai Shows (MOV-004)
        {
            id: "SHW-108",
            movieId: "MOV-004",
            theatreId: "THT-002",
            screenId: "SCR-005",
            date: "2026-08-28",
            startTime: "04:30 PM",
            endTime: "06:45 PM",
            showType: "Regular",
            ticketPrice: 150,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "C1", "C2"],
            status: "Available"
        },
        // Kottukkaali Shows (MOV-005)
        {
            id: "SHW-109",
            movieId: "MOV-005",
            theatreId: "THT-004",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "09:15 PM",
            endTime: "11:00 PM",
            showType: "Regular",
            ticketPrice: 140,
            totalSeats: 48,
            bookedSeats: ["A3", "A4"],
            status: "Available"
        },
        // Vettaiyan Shows (MOV-006)
        {
            id: "SHW-110",
            movieId: "MOV-006",
            theatreId: "THT-001",
            screenId: "SCR-002",
            date: "2026-08-28",
            startTime: "05:00 PM",
            endTime: "07:48 PM",
            showType: "Regular",
            ticketPrice: 190,
            totalSeats: 48,
            bookedSeats: ["A3", "A4", "B1", "B2", "C5", "C6", "E3", "E4"],
            status: "Available"
        },
        {
            id: "SHW-111",
            movieId: "MOV-006",
            theatreId: "THT-001",
            screenId: "SCR-004",
            date: "2026-08-28",
            startTime: "08:30 PM",
            endTime: "11:18 PM",
            showType: "Recliner",
            ticketPrice: 350,
            totalSeats: 48,
            bookedSeats: ["G1", "G2", "H1", "H2", "H3"],
            status: "Available"
        },
        // Amaran Shows (MOV-007)
        {
            id: "SHW-112",
            movieId: "MOV-007",
            theatreId: "THT-002",
            screenId: "SCR-005",
            date: "2026-08-28",
            startTime: "10:00 AM",
            endTime: "12:49 PM",
            showType: "Regular",
            ticketPrice: 160,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "B1", "B2", "C3", "C4"],
            status: "Available"
        },
        {
            id: "SHW-113",
            movieId: "MOV-007",
            theatreId: "THT-002",
            screenId: "SCR-006",
            date: "2026-08-28",
            startTime: "07:30 PM",
            endTime: "10:19 PM",
            showType: "IMAX",
            ticketPrice: 280,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "C1", "C2", "D3", "D4", "E1", "E2", "E3", "F4", "F5"],
            status: "Available"
        },
        // Raayan Shows (MOV-008)
        {
            id: "SHW-114",
            movieId: "MOV-008",
            theatreId: "THT-003",
            screenId: "SCR-007",
            date: "2026-08-28",
            startTime: "07:15 PM",
            endTime: "09:40 PM",
            showType: "IMAX",
            ticketPrice: 260,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "B1", "B2"],
            status: "Available"
        },
        // Maharaja Shows (MOV-009)
        {
            id: "SHW-115",
            movieId: "MOV-009",
            theatreId: "THT-005",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "06:30 PM",
            endTime: "08:51 PM",
            showType: "Regular",
            ticketPrice: 140,
            totalSeats: 48,
            bookedSeats: ["A1", "A2", "B3", "B4"],
            status: "Available"
        },
        // Garudan Shows (MOV-010)
        {
            id: "SHW-116",
            movieId: "MOV-010",
            theatreId: "THT-006",
            screenId: "SCR-001",
            date: "2026-08-28",
            startTime: "08:00 PM",
            endTime: "10:14 PM",
            showType: "Regular",
            ticketPrice: 140,
            totalSeats: 48,
            bookedSeats: ["C1", "C2", "D3", "D4"],
            status: "Available"
        }
    ],

    // Existing Pega Cases
    cases: [
        {
            pyID: "C-1001",
            bookingId: "CW20260828001",
            ticketId: "TKT-90412",
            customerId: "CUST-001",
            customerName: "Kavitha Raman",
            email: "kavitha.r@gmail.com",
            mobile: "+91 98401 23456",
            movieId: "MOV-001",
            movieTitle: "The Greatest of All Time (GOAT)",
            tamilTitle: "தி கிரேட்டஸ்ட் ஆஃப் ஆல் டைம்",
            theatreId: "THT-001",
            theatreName: "CineWave Luxe Cinemas – Chennai",
            location: "Chennai",
            screenId: "SCR-001",
            screenName: "Screen 1 – IMAX Laser",
            showId: "SHW-101",
            showDate: "2026-08-28",
            showTime: "10:30 AM",
            showType: "IMAX",
            ticketCategory: "VIP",
            ticketCount: 2,
            seats: ["H5", "H6"],
            ticketPrice: 280,
            categoryMultiplier: 1.5,
            subtotal: 840,
            convenienceFee: 80,
            taxAmount: 151.2,
            totalAmount: 1071.2,
            pyStatusWork: "Resolved-Completed",
            currentStageIndex: 7,
            assignedWorkbasket: "Premium Cinema Team",
            routingReason: "Auto-routed via US-010: Show Type = IMAX -> Premium Cinema Team",
            createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
            slaGoalMinutes: 10,
            slaDeadlineMinutes: 30,
            urgency: 40,
            slaStatus: "Within SLA",
            rejectionReason: "",
            auditTrail: [
                { time: "45 mins ago", actor: "Kavitha Raman (Customer)", action: "Booking request submitted (US-001)", stage: "Submit Booking Request" },
                { time: "44 mins ago", actor: "Pega Engine (System)", action: "Show seats validated & locked (US-002)", stage: "Check Show Availability" },
                { time: "44 mins ago", actor: "Pega Engine (System)", action: "Cost calculated: ₹1,071.20 (US-003)", stage: "Calculate Booking Cost" },
                { time: "43 mins ago", actor: "Kavitha Raman (Customer)", action: "Customer confirmed booking details (US-004)", stage: "Customer Confirmation" },
                { time: "42 mins ago", actor: "Pega Routing Router", action: "Case routed to 'Premium Cinema Team' (US-010)", stage: "Route Case" },
                { time: "38 mins ago", actor: "Arun (Staff - Premium Team)", action: "Booking approved & processed (US-006 & US-007)", stage: "Process Ticket Booking" },
                { time: "38 mins ago", actor: "Pega Notification Engine", action: "SMS & Email sent with QR Ticket (US-008)", stage: "Notify Customer" },
                { time: "38 mins ago", actor: "Pega Engine (System)", action: "Case Resolved-Completed", stage: "Case Completion" }
            ]
        },
        {
            pyID: "C-1002",
            bookingId: "CW20260828002",
            ticketId: "TKT-82941",
            customerId: "CUST-002",
            customerName: "Kathirvel T",
            email: "kathirvel.dev@cinewave.in",
            mobile: "+91 94432 98765",
            movieId: "MOV-006",
            movieTitle: "Vettaiyan",
            tamilTitle: "வேட்டையன்",
            theatreId: "THT-002",
            theatreName: "CineWave Grand Cineplex – Madurai",
            location: "Madurai",
            screenId: "SCR-006",
            screenName: "Screen 2 – IMAX Grand",
            showId: "SHW-113",
            showDate: "2026-08-28",
            showTime: "07:30 PM",
            showType: "IMAX",
            ticketCategory: "Premium",
            ticketCount: 3,
            seats: ["E1", "E2", "E3"],
            ticketPrice: 280,
            categoryMultiplier: 1.25,
            subtotal: 1050,
            convenienceFee: 120,
            taxAmount: 189,
            totalAmount: 1359,
            pyStatusWork: "Resolved-Completed",
            currentStageIndex: 7,
            assignedWorkbasket: "Premium Cinema Team",
            routingReason: "Auto-routed via US-010: Show Type = IMAX -> Premium Cinema Team",
            createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
            slaGoalMinutes: 10,
            slaDeadlineMinutes: 30,
            urgency: 25,
            slaStatus: "Within SLA",
            rejectionReason: "",
            auditTrail: [
                { time: "25 mins ago", actor: "Kathirvel T (Customer)", action: "Submitted VIP booking request", stage: "Submit Booking Request" },
                { time: "24 mins ago", actor: "Pega Engine", action: "Calculated ₹1,359 with IMAX premium", stage: "Calculate Booking Cost" },
                { time: "23 mins ago", actor: "Kathirvel T", action: "Confirmed details", stage: "Customer Confirmation" },
                { time: "20 mins ago", actor: "Meena (Staff)", action: "Approved and generated TKT-82941", stage: "Process Ticket Booking" },
                { time: "20 mins ago", actor: "System", action: "Dispatched In-App and Email notifications", stage: "Notify Customer" }
            ]
        },
        {
            pyID: "C-1003",
            bookingId: "CW20260828003",
            ticketId: "",
            customerId: "CUST-003",
            customerName: "Praveen Kumar",
            email: "praveen.k@gmail.com",
            mobile: "+91 97890 54321",
            movieId: "MOV-007",
            movieTitle: "Amaran",
            tamilTitle: "அமரன்",
            theatreId: "THT-001",
            theatreName: "CineWave Luxe Cinemas – Chennai",
            location: "Chennai",
            screenId: "SCR-004",
            screenName: "Screen 4 – VIP Gold Class",
            showId: "SHW-111",
            showDate: "2026-08-28",
            showTime: "06:30 PM",
            showType: "Recliner",
            ticketCategory: "Recliner",
            ticketCount: 2,
            seats: ["G1", "G2"],
            ticketPrice: 350,
            categoryMultiplier: 1.4,
            subtotal: 980,
            convenienceFee: 80,
            taxAmount: 176.4,
            totalAmount: 1236.4,
            pyStatusWork: "Pending-Review",
            currentStageIndex: 3,
            assignedWorkbasket: "Premium Seating Team",
            routingReason: "Auto-routed via US-010: Show Type = Recliner -> Premium Seating Team",
            createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
            slaGoalMinutes: 10,
            slaDeadlineMinutes: 30,
            urgency: 65,
            slaStatus: "Approaching Deadline",
            rejectionReason: "",
            auditTrail: [
                { time: "14 mins ago", actor: "Praveen Kumar (Customer)", action: "Submitted Recliner booking request", stage: "Submit Booking Request" },
                { time: "13 mins ago", actor: "Pega Engine", action: "Show seats verified. Calculated ₹1,236.40", stage: "Calculate Booking Cost" },
                { time: "12 mins ago", actor: "Praveen Kumar", action: "Confirmed details", stage: "Customer Confirmation" },
                { time: "12 mins ago", actor: "Pega Router", action: "Routed to 'Premium Seating Team' (US-010)", stage: "Route Case" },
                { time: "4 mins ago", actor: "SLA Monitor", action: "SLA Goal passed (10m). Urgency increased to 65. Warning badge set.", stage: "SLA Escalation" }
            ]
        }
    ],

    // Routing Workbaskets
    workbaskets: [
        { id: "WB-IMAX", name: "Premium Cinema Team", showType: "IMAX", description: "Specialized team managing high-tier IMAX Screen experiences", count: 1 },
        { id: "WB-VIP", name: "VIP Booking Team", showType: "VIP", description: "Handles 4DX, VIP Lounge and special requests", count: 0 },
        { id: "WB-RECLINER", name: "Premium Seating Team", showType: "Recliner", description: "Oversees Gold Class and Recliner Loungers", count: 1 },
        { id: "WB-REGULAR", name: "Standard Booking Team", showType: "Regular", description: "Standard Dolby Atmos & 2K screens bookings", count: 0 }
    ],

    // SLA Rules
    slaConfig: {
        goalMinutes: 10,
        deadlineMinutes: 30,
        passedDeadlineMinutes: 45,
        intervals: [
            { range: "0–10 mins", status: "Within SLA", badgeClass: "badge-success", urgencyRange: "0–40" },
            { range: "10–20 mins", status: "Approaching Deadline", badgeClass: "badge-warning", urgencyRange: "41–70" },
            { range: "20–30 mins", status: "High Priority", badgeClass: "badge-danger", urgencyRange: "71–89" },
            { range: "30+ mins", status: "SLA Breached", badgeClass: "badge-breached", urgencyRange: "90–100" }
        ]
    },

    // Pega Lifecycle Stages
    caseStages: [
        { index: 0, name: "Submit Booking Request", desc: "US-001: Capture Customer & Ticket Details" },
        { index: 1, name: "Check Show Availability", desc: "US-002: Real-time Seat Validation" },
        { index: 2, name: "Calculate Booking Cost", desc: "US-003: Automated Pricing Formula" },
        { index: 3, name: "Review Booking Details", desc: "US-006: Staff Review & Case Routing (US-010)" },
        { index: 4, name: "Customer Confirmation", desc: "US-004: Mandatory Customer Review & Ack" },
        { index: 5, name: "Process Ticket Booking", desc: "US-007: Seat Locking & Payment Processing" },
        { index: 6, name: "Generate Ticket", desc: "Digital QR Ticket & Confirmation" },
        { index: 7, name: "Notify Customer", desc: "US-008: Multi-channel SMS/Email/In-App Alert" }
    ],

    // Notifications
    notifications: [
        {
            id: "NOTIF-1",
            title: "Booking Confirmed - GOAT",
            channel: "SMS & Email",
            time: "45 mins ago",
            recipient: "+91 98401 23456 | kavitha.r@gmail.com",
            message: "CineWave: Your booking CW20260828001 for The Greatest of All Time at CineWave Luxe Chennai on 28 Aug 10:30 AM is confirmed! Seats: H5, H6. Ticket: TKT-90412.",
            read: false
        },
        {
            id: "NOTIF-2",
            title: "Booking Confirmed - Vettaiyan",
            channel: "SMS & In-App",
            time: "20 mins ago",
            recipient: "+91 94432 98765 | kathirvel.dev@cinewave.in",
            message: "CineWave: Your booking CW20260828002 for Vettaiyan (IMAX Grand) at Madurai is confirmed! Seats: E1, E2, E3. Ticket: TKT-82941.",
            read: false
        }
    ],

    // Registered normal users for login & sign-up simulation
    users: []
};
